services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql/mysql-server
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'Minutesofmeeting'

